### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by hadyrashwan** [aleferna12/colordict#2]
We are getting this error in the last month
```
Installing colordict...
Error:  An error occurred while installing colordict!
Error text: 
ERROR: Could not find a version that satisfies the requirement colordict (from versions: none)
ERROR: No matching distribution found for colordict

✘ Installation Failed 
```
tried using pipenv and using pip.

**Comment by hadyrashwan** [comment]
We were using the package in one line so we replaced that line with static color array. 
Let me know if I can help in testing the package.

**Comment by aleferna12** [comment]
I had messed up the PyPi repo. It should be working again now 👍

**Comment by vermavinay982** [comment]
@aleferna12  Its still not working, 0.2.3 version is present on pypi - but some packages require 1.2.5 version of colordict.

**Comment by vermavinay982** [comment]
Thanks for creating and providing this package, colordict=1.2.6 is working perfectly now.
